# Generated by Django 4.1.3 on 2023-01-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagemantapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='studcourse',
            new_name='bookname',
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='startdate',
            field=models.DateField(),
        ),
    ]
