# Generated by Django 4.1.3 on 2023-01-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagemantapp', '0002_rename_studcourse_issuebook_bookname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='bookname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagemantapp.book'),
        ),
    ]
